name: streamflow
version: "1.0.0"
config-version: 2

profile: streamflow

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  streamflow:
    staging:
      +materialized: incremental
      +schema: silver
      +tags: ["staging"]
    intermediate:
      +materialized: table
      +schema: silver
      +tags: ["intermediate"]
    marts:
      +materialized: table
      +schema: gold
      +tags: ["marts"]
