streamflow:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'streamflow-pg-rw.streamflow-data.svc.cluster.local') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'streamflow') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'streamflow') }}"
      schema: public
      threads: 2
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'streamflow') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'streamflow') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'streamflow') }}"
      schema: public
      threads: 2
